features gezag meerderjarige
BRP-API/brp-api-gezag pull request #151
Opened 2024-10-18 14:28 UTC by fsamwel

basis features die tonen dat gezag van een meerderjarige over eigen kinderen geleverd moet worden

2024-10-18 15:00 UTC, CathyDingemanse approved these changes
Lijkt mij prima. Super goed leesbaar en begrijpelijk. Hoop dat Henk en Ingrid er net zo over denken.

2024-12-20 12:26 UTC, FrozenSync requested changes
Enkele foutjes geconstateerd in de features.

2024-12-20 12:26 UTC, FrozenSync commented on features/specs/gezag-meerderjarige/gezag-kind-niet-te-bepalen.feature
> +      | burgerservicenummer | 000000036 |
```suggestion
      | burgerservicenummer | 000000012 |
```

Het is de bedoeling om te laten zien wat er gebeurd wanneer gezag wordt gevraagd over kinderen vanuit het perspectief van de ouder (meerderjarige). Volgens mij hoort hier dan de burgerservicenummer van Ingrid in te staan.

2024-12-20 12:26 UTC, FrozenSync commented on features/specs/gezag-meerderjarige/gezag-meerderjarige-over-kinderen.feature
> +      | burgerservicenummer | 000000024 |
```suggestion

```

De scenario schetst een gezin die bestaat uit een kind (000000036) met een ouder (000000012). Een tweede ouder (000000024) komt niet voor.

2024-12-20 12:57 UTC, FrozenSync commented on features/specs/gezag-meerderjarige/gezag-meerderjarige-over-kinderen.feature
> +      | burgerservicenummer | 000000024 |
```suggestion

```

De scenario schetst een gezin die bestaat uit een kind (000000036) met een ouder (000000012). Een tweede ouder (000000024) komt niet voor.

2024-12-20 12:57 UTC, FrozenSync commented on features/specs/gezag-meerderjarige/gezag-meerderjarige-over-kinderen.feature
> +      | burgerservicenummer | 000000024 |
Outdated door reformat. Vernieuwe suggestie in https://github.com/BRP-API/brp-api-gezag/pull/151#discussion_r1893910642 .

2025-01-28 09:00 UTC, CathyDingemanse reviewed
Henk en Ingrid migreren richting Sesamstraat

2025-01-30 10:02 UTC, fsamwel commented on features/specs/gezag-meerderjarige/gezag-kind-niet-te-bepalen.feature
> +      | burgerservicenummer | 000000036 |
opgelost

2025-01-30 10:04 UTC, fsamwel commented on features/specs/gezag-meerderjarige/gezag-meerderjarige-over-kinderen.feature
> +      | burgerservicenummer | 000000024 |
klopt, moest eenhoofdig ouderlijk gezag zijn, is opgelost

2025-01-30 10:04 UTC, merged